services:
  web:
    build: .
    ports:
      - "80:8000"
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/organization_db
#    depends_on:
#      - db
    volumes:
      - .:/app

  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=organization_db
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres_data:/var/lib/postgresql/data

  pgadmin:
    restart: always
    container_name: pgadmin
    image: dpage/pgadmin4:9.9.0
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin@email.com
      PGADMIN_DEFAULT_PASSWORD: 9tkgWIxz3nknyoIlBQYL
    volumes:
      - ./data/pgdata:/var/lib/postgresql/data/pgdata
    ports:
      - "28080:80"


volumes:
  postgres_data: